import Wrapper from '@/components/Wrapper'
import Head from 'next/head'
import React from 'react'

export default function Home() {
  return (
    <>
      <Head >
        <title>Maverick - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper className='text-center flex flex-col justify-center'>
        <div className='h-full'>
          <div>
            {/* Heading */}
            <h1 className='h1'>Book. Perfect. {" "}
              <span className='text-Red'>Ride.</span>
            </h1>

            {/* Subtitle */}
            <p className='text-Black mx-auto max-w-xl flex justify-center'>
            Car Dealer é o tema WordPress premium para concessionárias de automóveis mais atraente, criativo, moderno e multifuncional. Ideal para sites de concessionárias, empresas ou sites corporativos. Expresse seu estilo na estrada com nossas diversas variações de cores de veículos, oferecendo opções personalizadas para cada viagem. Melhore os visuais com pontos interativos, fornecendo detalhes e criando narrativas envolventes dentro de suas imagens sem esforço.
            </p>

            {/* Button */}

            <div className='flex gap-4 justify-center mt-8'>
              <button className='flex rounded-full bg-Red px-6 py-2.5 text-sm font-normal hover:bg-Black transition-all duration-300 text-White'>Ver Detalhes</button>
              <button className='flex rounded-full bg-Red px-6 py-2.5 text-sm font-normal hover:bg-Black transition-all duration-300 text-White'>Alugar</button>
            </div>

          </div>
        </div>
      </Wrapper>
    </>
  )
}
